/*
 * Copyright 2026 Karlsruhe Institute of Technology.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
////////////////////////////////////////////////////////////////////////////////
// Build jar file with all tests executed.
// Before releasing code you should at least once run all the tests.
////////////////////////////////////////////////////////////////////////////////
println "Using complete profile for building '${name}'"

test {
    println 'Execute all tests...'
    outputs.dir snippetsDir
    // Allow access to internal methods used by powerMockito
    // Will fail with Java17
    if (JavaVersion.current().isJava9Compatible()) {
        println 'Allow access to private methods...'
        jvmArgs '--illegal-access=permit'
    }
    if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_16)) {
        println 'Allow access to private methods of package java.io...'
        jvmArgs '--add-opens=java.base/java.io=ALL-UNNAMED'
   }
    // Execute all tests
    include '**/*'
}

// Generate coverage report
jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = false
    }
    afterEvaluate {
        //exclude some classes/package from code coverage report
        classDirectories.setFrom(files(classDirectories.files.collect {
                    fileTree(dir: it, exclude: [\
            '**/SchemaSynchronization*'
                        ])
                }))
    }
}
